### ISSUE TITLE
提供更高自由度的文件自动重命名方式

### ISSUE THREAD

**Issue by longjuan** [halo-dev/plugin-s3#110]
目前文件自动重命名方式只提供了几种重命名规则，部分规则实用度不高，因此希望设计一种方式来给用户自定义重命名规则。

**Comment by longjuan** [comment]
我的想法是提供两个选项：

**自动重命名规则**
提供以下占位符：
- ${filename}: 原文件名
- ${uuid:with_dash}: 带分隔线的UUID格式
- ${uuid:no_dash}: 无分隔线的UUID格式
- ${timestamp:sec}: 秒级时间戳
- ${timestamp:ms}: 毫秒级时间戳
- ${year}: 当前年份
- ${month}: 当前月份
- ${day}: 当前日期
- ${weekday}: 当前星期几
- ${hour}: 当前小时
- ${minute}: 当前分钟
- ${second}: 当前秒数
- ${millisecond}: 当前毫秒数
- ${random:num:X}: X位随机数字（例如，${random:num:4}生成一个4位的随机数字）
- ${random:alpha:X}: X位随机字母（例如，${random:alpha:5}生成一个5位的随机字母串）
- ${random:alphanumeric:X}: X位随机字母数字组合（例如，${random:alphanumeric:8}生成一个8位的随机字母数字串）
默认为`${filename}`

**文件名冲突措施**
默认为`_${random:alphanumeric:4}`，留空为直接报错。

参考的是：
![image](https://github.com/halo-dev/plugin-s3/assets/28662535/57df809d-ec7e-4626-ba9c-febae07e259a)

/ping @halo-dev/sig-halo 有什么更好的想法？

**Comment by JohnNiang** [comment]
Hi @longjuan ，我认为以上规则已经非常灵活，不过仍然建议默认提供几种常用的“自动重命名方式”。
