### ISSUE TITLE
halo 2.12 七牛云同步异常

### ISSUE THREAD

**Issue by daodaoshi** [halo-dev/plugin-s3#122]
更新2.12后，七牛云上传文件后链接存储异常，无法预览和使用文件；查看七牛云空间存储，内容已上传，并能正常查看、使用；
回退2.11后，功能正常使用。
<img width="626" alt="Snipaste_2024-02-27_13-38-32" src="https://github.com/halo-dev/plugin-s3/assets/58846742/3fe4160e-3d90-41d8-927c-02c568b7d3d5">

**Comment by ruibaby** [comment]
具体版本是？

**Comment by daodaoshi** [comment]
> 具体版本是？

halo : 2.12.0
对象存储（Amazon S3 协议）: 1.7.0

**Comment by ruibaby** [comment]
> > 具体版本是？
> 
> halo : 2.12.0 对象存储（Amazon S3 协议）: 1.7.0

升级到 2.12.2 以上试试。

**Comment by daodaoshi** [comment]
> > > 具体版本是？
> > 
> > 
> > halo : 2.12.0 对象存储（Amazon S3 协议）: 1.7.0
> 
> 升级到 2.12.2 以上试试。

升级到2.12.4解决问题，感谢大佬~🙌
