### ISSUE TITLE
七牛上传附件稍微大点 就报504错误

### ISSUE THREAD

**Issue by scychina** [halo-dev/plugin-s3#125]
附件小上传可以成功，但是稍微大点就报错，报错如下
![111222](https://github.com/halo-dev/plugin-s3/assets/6381835/10059623-b37e-428c-91a4-4d8ffc62879a)
麻烦帮忙看下谢谢

**Comment by longjuan** [comment]
检查一下反向代理是否设置了接口超时时间

**Comment by scychina** [comment]
没有设置，我刚刚设置了一下超时时间，
很长，还是无法上传文件，然后4m以内的都可以上传 ，再大点就无法上传了
![2333](https://github.com/halo-dev/plugin-s3/assets/6381835/dac473f2-65a2-4f05-8276-93e971888380)

**Comment by longjuan** [comment]
halo和插件是没有设置超时时间的，所以报超时错误可能是前面的反向代理/CDN报的504错误，请检查相关配置。

**Comment by scychina** [comment]
好的多谢 我这边再检查下

**Comment by lfmwuy** [comment]
我也是这样, 不过我是cloudflare

**Comment by lfmwuy** [comment]
解决了
尝试在nginx的proxy中加入
proxy_read_timeout 600;
这样

**Comment by lfmwuy** [comment]
猜测原因可能是, 我不懂代码
我上传文件->博客服务器->S3
我传到博客服务器是可以的
但是由博客服务器传到s3, 需要受限于博客服务器的上传带宽, 我的是3M, 传一个50M的文件, 可能都需要很久
默认是60s超时, 所以会导致nginx 504 timout

**Comment by JohnNiang** [comment]
Please refer to <https://github.com/halo-dev/plugin-s3/issues/125#issuecomment-2293071043>.

/close
/kind support
