### ISSUE TITLE
添加配置验证功能

### ISSUE THREAD

**Issue by longjuan** [halo-dev/plugin-s3#132]
https://github.com/halo-dev/halo/releases/tag/v2.14.0-rc.1 提供了验证表单
目前可适配，但有两种验证方法可选：
1. 仅使用list测试是否能正常访问对象存储服务，缺点是部分minio用户会发生验证通过而无法上传的问题
2. 使用list、MultipartUpload、headObject、deleteObject完整验证全流程，缺点是有可能产生更多费用、速度稍慢。

大家倾向哪一种
@halo-dev/sig-halo

**Comment by guqing** [comment]
我觉得 或许只需要考虑能上传并可读就行，我看很多系统在验证配置这方面会选择上传一张较小的图到存储并验证能访问到图片链接就表示配置成功
