### ISSUE TITLE
在谷歌浏览器无法查看图片

### ISSUE THREAD

**Issue by Jacen-jiajia** [halo-dev/plugin-s3#133]
我绑定了七牛云的对象存储, 然后上传都是正常的, 也绑定的存储的域名,但是在谷歌浏览器查看的时候,一直访问的是https的请求,无法访问http的,  我换成火狐就可以了, 这个怎么解决呢?
![12](https://github.com/halo-dev/plugin-s3/assets/57289598/9237f947-47f5-4f48-af4d-a9643b0c13a3)
![Snipaste_2024-04-09_14-33-18](https://github.com/halo-dev/plugin-s3/assets/57289598/3a48d761-2b68-4608-a0f6-03d9edbaca61)

**Comment by longjuan** [comment]
你halo是不是加了https？谷歌可能会阻止https网站访问http资源，请检查一下。

**Comment by ruibaby** [comment]
这是 Chrome 的策略，和插件以及 Halo 都无关，如果你一定想要在 https 网站下加载 http 资源，你可以在 Halo 设置 -> 代码注入的全局 head 中添加这个 meta 标签：

```html
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
```

但不是特别推荐。

**Comment by Jacen-jiajia** [comment]
好的,谢谢了, 目前我已经把这个资源的换成https的了, 原来用的七牛云https的得需要花钱, 现在换成又拍云可以免费用https的.
