### ISSUE TITLE
一个很偏的需求，阿里云内网上传，代理阿里云内网在互联网访问

### ISSUE THREAD

**Issue by ariwori** [halo-dev/plugin-s3#139]
这样可以免掉OSS的流量费

**Comment by longjuan** [comment]
本插件上传附件的时候是使用Halo所在服务器上传。

你是想要访问附件的时候使用Halo所在服务器进行代理，走内网流出流量是吗？

**Comment by ariwori** [comment]
对的

**Comment by ariwori** [comment]
> 对的



> 本插件上传附件的时候是使用Halo所在服务器上传。
> 
> 你是想要访问附件的时候使用Halo所在服务器进行代理，走内网流出流量是吗？

是的，这个可以用nginx代理完成，但是插件的话没办法配置代理的域名来访问OSS

**Comment by ariwori** [comment]
有时候小站点就想降低成本

**Comment by longjuan** [comment]
> 是的，这个可以用nginx代理完成，但是插件的话没办法配置代理的域名来访问OSS

在绑定域名里填写nginx代理后的域名就行

**Comment by ariwori** [comment]
试了可以，谢谢，我还以为那个是云服务商的自定义域名呢

**Comment by longjuan** [comment]
> 试了可以，谢谢，我还以为那个是云服务商的自定义域名呢

/close
