### ISSUE TITLE
建议关联S3文件增加搜索功能

### ISSUE THREAD

**Issue by Litbay** [halo-dev/plugin-s3#142]
如题，有一些文件不想关联，然后对象存储文件一多之后就很难找到想关联的文件，麻烦加一个通过文件名搜索未关联文件的功能，谢谢

**Comment by longjuan** [comment]
S3不支持模糊搜索，只支持前缀搜索

**Comment by Litbay** [comment]
> S3不支持模糊搜索，只支持前缀搜索

能搜前缀也好啊，用着也方便很多
