### ISSUE TITLE
突然提示不能用了

### ISSUE THREAD

**Issue by TenTh0usand** [halo-dev/plugin-s3#143]
![image](https://github.com/halo-dev/plugin-s3/assets/148879701/fd47bc1a-1268-4e40-87c8-b34d15d9cd40)
好久没用了，传图的时候发现无法上传，检查发现附件中已经设置好的腾讯云cos储存策略无法设置，点击增加储存策略也只能添加本地储存

**Comment by longjuan** [comment]
你的Halo版本是多少呢？
尝试重启Halo或者更新Halo到最新版本。

**Comment by TenTh0usand** [comment]
已解决
halo 版本是2.14.0，重启halo就解决了，谢谢
