### ISSUE TITLE
插件没有拼接Bucket桶名称

### ISSUE THREAD

**Issue by QingFeng-awa** [halo-dev/plugin-s3#144]
我的存储桶正常访问名称应是https://cn-sy1.rains3.com/xtremewave/{文件名}
但插件的访问地址却是https://cn-sy1.rains3.com/{文件名}
我个人认为是因为插件没有拼接Bucket导致的
我的配置如下:

- 名称:XtremeWaveOSS
- Bucket桶名称:XtremeWave
- Endpoint访问协议:HTTPS
- Endpoint访问风格:PathStyle
- EndPoint:cn-sy1.rains3.com
- AccessKeyID:不便透露
- AccessKeySecret:不便透露
- Region:默认
- 上传目录:默认
- 上传时重命名文件方式:保留原文件名
- 重复文件名处理方式:报错不上传
- 绑定域名协议:HTTPS
- 绑定域名(CDN域名):cn-sy1.rains3.com

**Comment by longjuan** [comment]
绑定域名(CDN域名) 不填或者填cn-sy1.rains3.com/xtremewave
