### ISSUE TITLE
S3关联文件不能被选择与预览

### ISSUE THREAD

**Issue by QingFeng-awa** [halo-dev/plugin-s3#149]
### 系统信息
- 外部访问地址: https://www.xtreme.net.cn
- 启动时间: 2024-05-03 19:09
- 版本: 2.15.0
- 构建时间: 2024-04-30 16:27
- Git Commit: 1582a62
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 5.15.0-105-generic
- 已激活主题: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [Trailing Slash](https://github.com/halo-sigs/plugin-trailing-slash)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [文本绘图](https://github.com/halo-sigs/plugin-text-diagram)
  - [Meilisearch](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [应用市场](https://www.halo.run/store/apps/app-VYJbF)
### 运行方式
Docker
### 发生问题的详细描述
使用S3关联原本就在对象存储内的PNG图像文件,并且(在默认编辑器内添加图片时)附件库无法选择并且无法被预览。
通过Halo上传的文件可以正常预览,这令我感到很奇怪。
### 附加信息
S3关联PNG图像文件的文件类型被识别成了`application/octet-stream`,但通过Halo上传的PNG图像文件被正常识别为`image/png`。
![image](https://github.com/halo-dev/plugin-s3/assets/151742581/3089fd5c-b547-499d-92e6-4ef730b303da)
上图为通过S3关联的PNG文件信息。
![image](https://github.com/halo-dev/plugin-s3/assets/151742581/a9525fc7-bad9-4ad3-9126-83236aaa5068)
上图为通过Halo上传的PNG文件信息。
> 批量关联S3文件时包含非PNG文件(Json、Dll、Zip、Woff2)。
> 这是造成错误的原因吗?

**Comment by longjuan** [comment]
当文件上传到S3时，如果没有明确指定`ContentType`，S3会默认将其设置为`application/octet-stream`。这个`ContentType`是一个通用的二进制文件类型，它告诉浏览器文件是一种二进制数据，但并没有提供足够的信息来确定文件的具体类型和正确的处理方式。

浏览器接收到`application/octet-stream`时，通常无法确定如何正确显示文件，因为它不具备足够的上下文来识别文件的实际内容。因此，这并不是S3插件的功能限制，而是浏览器基于HTTP协议标准对`ContentType`的响应方式。

S3关联功能的作用是辅助于链接S3存储资源，并不涉及修改或指定上传到S3的文件的`ContentType`。为了解决这个问题，您需要在上传文件到S3时，确保设置了正确的`ContentType`。例如，如果您上传的是图片文件，应该在上传时设置`image/jpeg`或相应的`ContentType`。

**Comment by QingFeng-awa** [comment]
那么我该如何设置正确的`ContentType`呢?在对象存储服务商提供的面板中内设置吗?亦或者是通过Halo?

> 我使用[雨云](https://www.rainyun.com/home)对象存储为网站提供存储服务。
> 但是,在[雨云的对象存储文档](https://www.rainyun.com/docs/category/ros)中似乎并没有提供有关此问题的FAQ。

**Comment by QingFeng-awa** [comment]
雨云客服回复称不支持设置`ContentType`,这个issue算是结束了……
不过,我有点希望Halo能通过文件后缀名来判断文件的显示方式,但愿以后能做出来吧……

**Comment by longjuan** [comment]
正常对象存储都会支持设置ContentType的，同时上传工具也要支持自动设置这一字段。
在访问对应文件时对象存储会依据这个字段设置http响应头的，halo在这中间无法进行操作。
况且有些场景可能要主动设置ContentType为application/octet-stream达到一些需求，插件不会乱改用户的文件Header。
![image](https://github.com/halo-dev/plugin-s3/assets/28662535/a2071c48-6b04-4daf-986e-a656675ac3eb)
