### ISSUE TITLE
修改绑定域名怎么之后怎么修改之前的文件

### ISSUE THREAD

**Issue by zhdgzs** [halo-dev/plugin-s3#154]
同一个s3存储策略，之前上传了一批图片，绑定的域名是 file.pro.xxx.top:8752/notes
图床因为一些原因，必须修改域名
把策略修改了绑定域名，改成  file.expome.top/notes
但是之前的文件前缀无法修改，应该怎么处理？

**Comment by xindi520** [comment]
> 同一个s3存储策略，之前上传了一批图片，绑定的域名是 file.pro.xxx.top:8752/notes 图床因为一些原因，必须修改域名 把策略修改了绑定域名，改成 file.expome.top/notes 但是之前的文件前缀无法修改，应该怎么处理？

我也有这个疑惑，但是目前来看，只能手动一个一个改

**Comment by fu9809** [comment]
一个一个改怎么修改，找不到修改的位置

**Comment by xindi520** [comment]
> 一个一个改怎么修改，找不到修改的位置

点击图片的超链接，把里面的域名改了就好了

**Comment by fu9809** [comment]
没有可以编辑的地方啊
![img_v3_02bt_642ace8d-e3a6-4c27-ac22-895b1127660g](https://github.com/halo-dev/plugin-s3/assets/41773644/b79a3ac2-5da0-4e47-91ee-b5d0c9a644f0)

**Comment by longjuan** [comment]
目前推荐的做法是先对附件 **解除S3关联**，然后修改绑定域名后在 **S3关联** 功能中关联之前的文件

**Comment by longjuan** [comment]
Same https://github.com/halo-dev/plugin-s3/issues/62
