### ISSUE TITLE
大佬能否与123网盘做集成

### ISSUE THREAD

**Issue by Mr-dadong** [halo-dev/plugin-s3#156]
大佬能否与123网盘做集成，强烈支持大佬

**Comment by longjuan** [comment]
本插件是s3协议的插件，建议找社区支持

**Comment by ruibaby** [comment]
现在 Halo 社区已经有了集成 AList 存储的插件，应该可以通过 AList 接入 123 网盘。

https://github.com/halo-sigs/plugin-alist

/close
