### ISSUE TITLE
缤纷云上传报错524

### ISSUE THREAD

**Issue by Einstein-schrodinger** [halo-dev/plugin-s3#157]
小一点的图片可以上传成功，1M以上就会失败，请问可能是哪里的问题？
![image](https://github.com/halo-dev/plugin-s3/assets/62790820/895e035f-59bf-4089-ab0f-1fc7c5111fde)

**Comment by longjuan** [comment]
https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-5xx-errors/#error-524-a-timeout-occurred
看起来是你的网站接入了cloudflare，而上传大文件时超过cloudflare设置的超时时间，cloudflare返回524
