### ISSUE TITLE
有没有老哥有时间出个cloudflare R2挂载的图文教程啊，挂了半天挂不上，，

### ISSUE THREAD

**Issue by mnwfbo** [halo-dev/plugin-s3#158]

**Comment by JohnNiang** [comment]
region 记得设置为 `auto`。

> https://github.com/halo-dev/plugin-s3#region

**Comment by mnwfbo** [comment]
> region 记得设置为 。`auto`
> 
> > https://github.com/halo-dev/plugin-s3#region

太感谢老哥了，经老哥一指点立马挂上了！！
