### ISSUE TITLE
上传minio 图片avif格式，现在是application/octet-stream，需要上传时设置Content-Type 为 image/avif, 

### ISSUE THREAD

**Issue by oxygensohn** [halo-dev/plugin-s3#169]
如题：环境 halo 2.19.3

**Comment by longjuan** [comment]
插件的Content-Type转换使用spring的MediaTypeFactory，我看到spring已经更新了清单，可能会在spring6.2发布。
https://github.com/spring-projects/spring-framework/commit/cc3f4b87ff55846637035e225621f4e7a84d3531#diff-9d11bb1d4939ddec59912335e156384557110161760b2aa744701776962df6d9R647
后续如果halo项目更新spring到6.2版本即可支持。

**Comment by JohnNiang** [comment]
Halo 2.20.0 将会升级到 Spring Boot 3.4.0-M3，该版本已经包含了 Spring Framework 6.2.0-RC.1。

详情请参考：
- https://github.com/spring-projects/spring-boot/releases/tag/v3.4.0-M3
- https://github.com/halo-dev/halo/pull/6687

**Comment by longjuan** [comment]
我这边测试使用Halo 2.20.7 上传是 image/avif 了。
/close
