### ISSUE TITLE
添加Alist就报错

### ISSUE THREAD

**Issue by liuzhangqun886** [halo-dev/plugin-s3#174]
![Image](https://github.com/user-attachments/assets/d372797e-621d-4b3c-b7e8-d03183d28a23)
[_opt_1panel_apps_halo_halo_docker-compose.yml-20241022192003.log](https://github.com/user-attachments/files/17475257/_opt_1panel_apps_halo_halo_docker-compose.yml-20241022192003.log)
[halo-log-2024-10-22 19_21.log](https://github.com/user-attachments/files/17475264/halo-log-2024-10-22.19_21.log)

**Comment by JohnNiang** [comment]
Hi @liuzhangqun886 , 请不要在当前仓库下提交无关的 Issue。

Alist 的问题建议去 https://github.com/halo-sigs/plugin-alist/issues 提交。

/close
/triage unresolved
