### ISSUE TITLE
使用minio存储，附件库缩略图加载异常

### ISSUE THREAD

**Issue by lengchuanwen** [halo-dev/plugin-s3#176]
缩略图加载默认https协议，包括主题配置图片路径是http协议，但是网页加载时默认也是https协议
![Image](https://github.com/user-attachments/assets/ad2a00e7-05de-4f95-84d7-8aecee0eecc1)
![Image](https://github.com/user-attachments/assets/f721d448-bf55-4678-8071-0694fcf542b3)
![Image](https://github.com/user-attachments/assets/b503b104-f318-422a-9784-cf03f72c5d00)
![Image](https://github.com/user-attachments/assets/d7c938b9-f4fc-4c8d-9fb5-563c61d07539)

**Comment by ruibaby** [comment]
这是浏览器本身的行为，详见：

- https://blog.chromium.org/2023/08/towards-https-by-default.html
- https://superuser.com/questions/565409/how-to-stop-an-automatic-redirect-from-http-to-https-in-chrome

**Comment by lengchuanwen** [comment]
感谢
