### ISSUE TITLE
cloudflare R2 无法正确获取文件访问地址

### ISSUE THREAD

**Issue by sugar-zero** [halo-dev/plugin-s3#177]
R2无法公共读，需要带签名才能访问，但是返回的访问链接是直链方式
而R2的公共读仅限R2.dev域
![Image](https://github.com/user-attachments/assets/0973e699-b2e2-427d-97c1-bf8318f02a9b)
![Image](https://github.com/user-attachments/assets/8dbe370c-2707-4e0f-99c6-deb2aebddfd5)

**Comment by JohnNiang** [comment]
针对 R2 不能公共读的场景，我们建议采用“只存不读”使用，例如 Halo 系统备份。

虽然我们可以做到生成一个“分享”（预签）链接，但该链接始终是临时的，并不能保证永久可访问。例如 R2 分享链接过期时间最长只能设置 7 天，详情可参考 
- https://developers.cloudflare.com/r2/api/s3/presigned-urls/#:~:text=7%20days
- https://developers.cloudflare.com/r2/api/s3/presigned-urls/#limitations

**Comment by sugar-zero** [comment]
能否参考alist的重定向方式，每次读取用到R2存储文件时就重新签名，这样可以保证每次渲染返回的链接都是有效的
或者参考阿里云oss这种在只保存文件的key，查询数据时再计算加密返回签名链接?

**Comment by JohnNiang** [comment]
不过你提到的重定向功能倒是可以考虑，但这可能就不是当前插件所需要完成的事情了。当前插件已经实现了获取“分享”链接的方法。想要实现这个功能，得在 [Halo core ](https://github.com/halo-dev/halo)中完成，短期内可能没有这个计划。稍后我将在 Halo core 中提交新的 Issue 来描述这个功能。

**Comment by sugar-zero** [comment]
好的

**Comment by JohnNiang** [comment]
Supersedes by <https://github.com/halo-dev/halo/issues/6961>.

/close
