### ISSUE TITLE
【建议】希望在文章编辑器中直接粘贴的图片，也能直接上传到S3中

### ISSUE THREAD

**Issue by RonenWen** [halo-dev/plugin-s3#179]
在编辑文章的时候，会通过粘贴的方式插入图片。经过测试，这个似乎是直接上传到本地磁盘而非S3中。希望能够提供一个选项，选择所有附件的默认上传位置（例如上传到S3中）。

**Comment by ruibaby** [comment]
在 https://docs.halo.run/user-guide/settings#%E6%96%87%E7%AB%A0%E8%AE%BE%E7%BD%AE 配置附件存储策略即可。

**Comment by RonenWen** [comment]
感谢
