### ISSUE TITLE
1.3版本插件，会导致服务器卡死

### ISSUE THREAD

**Issue by gaoqiang0925** [halo-dev/plugin-s3#21]
1.3版本插件，会导致服务器卡死

**Comment by longjuan** [comment]
是安装的时候卡死还是上传文件的时候卡死？
最好能提供卡死前后的日志和机器配置相关信息。

**Comment by gaoqiang0925** [comment]
机器配置2c2h 4M 是在运行的时候出现服务器卡死，换成1.2.1之后没发现这个问题
![1](https://user-images.githubusercontent.com/115871514/218952158-4a2e4224-589c-4017-8afc-3b869fc6f3d4.png)
![2](https://user-images.githubusercontent.com/115871514/218952168-3bad76c1-eee1-40fe-a1f7-8eda6702f3a8.png)

上图为服务器卡死的时候CPU和 磁盘占用，磁盘达到  108341.821KB/s
服务器只有halo服务在运行

**Comment by gaoqiang0925** [comment]
我在卸载插件一个一个测试的时候，只有安装1.3后会出现这个问题，卸载后重新装1.2.1后，问题得到了解决。是不是1.3版本的文件检查导致的呢？

**Comment by longjuan** [comment]
理论上来说，此插件只有在文件上传的时候才会有读硬盘的行为，我这边一直用着没出现过这种情况。
如果你愿意，可以重新装上1.3版本的插件，观察还会不会又这种情况出现。

**Comment by longjuan** [comment]
如果有卡死那段的运行日志（在挂载的目录logs文件夹下），可以把日志附上来。

**Comment by longjuan** [comment]
请试一下1.4.0是否还存在问题
