### ISSUE TITLE
提个小需求，是否可行？

### ISSUE THREAD

**Issue by CnDaiL** [halo-dev/plugin-s3#26]
非常喜欢这个插件，非常好用，感谢官方。

然后有个小需求，就是我博客或者插件重新安装后，之前用 S3传到 桶里的图片 在插件内部就不显示了。

图片少的情况下，我一般都是删了所有图片，然后重新传。

1、能否支持一下，重新安装插件，有个按钮，点击后读取桶内图片，在插件端显示的功能呢？ 
2、就是在插件后台，我们设置了分组，但是在桶内却无法分别，能否上传文件的时候，自动设置或者修改 文件名，以达到区分分组的目的？ 然后在实现1的前提下， 我们读取桶内图片的时候，以前的分组，也自动回来了。

如果这俩功能能实现，我觉得，基本完美了。

我不知道，我是否表达清楚我的意思了。

**Comment by longjuan** [comment]
> 点击后读取桶内图片，在插件端显示的功能呢

就是导入桶中已有的图片，这个功能可以实现，但这样的做法好不好需要讨论。



> 能否上传文件的时候，自动设置或者修改 文件名，以达到区分分组的目的

这个用文件名去区分分组，我认为不太合适。
如果真的要实现区分分组，可以用对象存储的metadata里存储信息，但是目前插件无法感知分组的改变，因此这个功能目前实现不了。

**Comment by CnDaiL** [comment]
> > 点击后读取桶内图片，在插件端显示的功能呢
> 
> 就是导入桶中已有的图片，这个功能可以实现，但这样的做法好不好需要讨论。
> 
> > 能否上传文件的时候，自动设置或者修改 文件名，以达到区分分组的目的
> 
> 这个用文件名去区分分组，我认为不太合适。 如果真的要实现区分分组，可以用对象存储的metadata里存储信息，但是目前插件无法感知分组的改变，因此这个功能目前实现不了。

感谢官方回复，期待需求1的小功能。

**Comment by ruibaby** [comment]
> 然后有个小需求，就是我博客或者插件重新安装后，之前用 S3传到 桶里的图片 在插件内部就不显示了。

重装插件之后数据会丢？

@JohnNiang @longjuan @guqing

**Comment by guqing** [comment]
卸载应该是不会丢失之前已上传的图片吧，只有可能选择了卸载连同删除配置然后重新安装需要再配置之后才能查询到

**Comment by CnDaiL** [comment]
求更新呀，老板~~~

**Comment by longjuan** [comment]
已在 1.5.0 实现。
https://github.com/halo-dev/plugin-s3/releases/tag/1.5.0

/close
