### ISSUE TITLE
七牛云 会出现本地跟云端路径重叠 [本地url无法使用] error

### ISSUE THREAD

**Issue by FlyumMicro** [halo-dev/plugin-s3#27]
使用：七牛云 
本地：会出现url 会出现无拼接 Bucket 桶名称  导致本地图片url无法加载

错误：
**Bucket 桶名称：cn-south-1 
上传目录：默认不填写
最终插件生成url：http://xxxx.com/xx.img
实际七牛云那边url:  http://xxxx.com/cn-south-1/xx.img**

**Bucket 桶名称：cn-south-1 
上传目录：cn-south-1 
最终插件生成url：http://xxxx.com/cn-south-1/xx.img
实际七牛云那边url:  http://xxxx.com/cn-south-1/cn-south-1/xx.img   【怎么设置都是本地少一个cn-south-1】**

### 本地url： 域名+路径+图片 

**导致图片加载失败 希望解决**
这个是个bug 希望可以修复

![Snipaste_2023-03-10_20-48-36](https://user-images.githubusercontent.com/50798769/224320784-96590261-dd2b-4e87-8f8e-51b963c3b2fd.png)

![Snipaste_2023-03-10_20-04-58](https://user-images.githubusercontent.com/50798769/224320554-c1a6fddf-78c9-4588-b6ed-fbe7e66727b6.png)

![image](https://user-images.githubusercontent.com/50798769/224320392-61d9150d-422f-4a56-b610-7dee2235e504.png)

![Snipaste_2023-03-10_20-47-11](https://user-images.githubusercontent.com/50798769/224320529-065b7649-127d-4d52-9958-01eab4157216.png)

云端路径

![image](https://user-images.githubusercontent.com/50798769/224321873-1918b532-9900-45b2-bfd2-967cdf4ac30b.png)

**Comment by longjuan** [comment]
请参照[README.md](https://github.com/halo-sigs/plugin-s3#readme)配置插件
我这边的配置：
![image](https://user-images.githubusercontent.com/28662535/224468205-39b98097-18a6-482b-9783-da024e657093.png)
![image](https://user-images.githubusercontent.com/28662535/224468212-f91d9bcd-4f46-4aa2-85ee-31a3a57fe370.png)

**Comment by longjuan** [comment]
非插件问题。

/close
