### ISSUE TITLE
七牛云查看图片报错

### ISSUE THREAD

**Issue by JinLiGame** [halo-dev/plugin-s3#44]
<Error>
<Code>NotSupportAnonymous</Code>
<Message>request must have signature info</Message>
<Resource>/QQ浏览器截图20220225103916.png</Resource>
<RequestId>h30AAADtWUgneWwX</RequestId>
</Error>

**Comment by longjuan** [comment]
这是因为你的桶的读权限是私有的，不能直接访问。
七牛云有免费的cdn，请填写对应cdn地址。

**Comment by longjuan** [comment]
非插件问题。

/close
