### ISSUE TITLE
能不能加个添加图片处理后缀的，oss图片处理需要在地址后加上处理接口

### ISSUE THREAD

**Issue by hongyuyi** [halo-dev/plugin-s3#68]
比如七牛云的?imageView2/0/format/webp/q/75
图片地址就是
myexample.png?imageView2/0/format/webp/q/75

阿里云和其他oss同理

在总体的链接后加个网址后缀。
就比如picgo上能加网址后缀这种。
![image](https://github.com/halo-sigs/plugin-s3/assets/143865214/4aedc9e7-b454-401e-9be5-1963c355b1db)

**Comment by longjuan** [comment]
这个后缀设置了以后，后续上传的所有文件都会加上这个，无论什么格式的文件，这可能会导致错误。
