### ISSUE TITLE
建议可以增加一个自动创建年份的目录。目前上传是全部上传到桶的根目录下面。

### ISSUE THREAD

**Issue by lcese** [halo-dev/plugin-s3#69]
建议可以增加一个自动创建年份的目录。目前上传是全部上传到桶的根目录下面。

**Comment by JohnNiang** [comment]
插件是支持在创建“存储策略”的时候设置“上传目录”的。

**Comment by hbulletandwebshow** [comment]
> 插件是支持在创建“存储策略”的时候设置“上传目录”的。

这个我知道。后台设置是有。但如果到了2024年呢。2025年呢。换了插件目录，后台附件图片地址是不是也跟着变了呢。

**Comment by longjuan** [comment]
在上传目录中支持 `${year}` `${month}` `${day}` 变量替换，如何？
/ping @JohnNiang

**Comment by longjuan** [comment]
@AccAutomaton 有兴趣吗？
搞个方法替换location的 `${year}` `${month}` `${day}`，然后这些调用换成新的方法 
![image](https://github.com/halo-sigs/plugin-s3/assets/28662535/a127e616-41b5-4bc3-a4a5-8bcc545c45c4)

**Comment by JohnNiang** [comment]
> 在上传目录中支持 `${year}` `${month}` `${day}` 变量替换，如何？ /ping @JohnNiang

LGTM

**Comment by AccAutomaton** [comment]
> @AccAutomaton 有兴趣吗？
> 搞个方法替换location的 `${year}` `${month}` `${day}`，然后这些调用换成新的方法 
> ![image](https://github.com/halo-sigs/plugin-s3/assets/28662535/a127e616-41b5-4bc3-a4a5-8bcc545c45c4)
> 

感觉不错
