### ISSUE TITLE
Halo 2.10 版本中关联S3文件的全选复选框消失

### ISSUE THREAD

**Issue by longjuan** [halo-dev/plugin-s3#82]
复选框消失：
![image](https://github.com/halo-dev/plugin-s3/assets/28662535/784cf874-1cf9-4e85-8763-f1eed4ae304c)
正常状态：
![image](https://github.com/halo-dev/plugin-s3/assets/28662535/8b8fd8fa-a4c0-447e-8258-7e1922516316)

经排查，与 <https://github.com/halo-dev/halo/pull/4598> 有关。

**Comment by longjuan** [comment]
@ruibaby 有空帮忙看下，没看出哪里的问题，在 <https://github.com/halo-dev/halo/pull/4598> 之后就有问题。

**Comment by ruibaby** [comment]
应该是和这行有关：https://github.com/halo-dev/plugin-s3/blob/0265a71c83c677fd87eb02839958a4142dc72e23/console/src/views/HomeView.vue#L248

`system:users:aaa` 似乎没有在任何的 role template 中定义，如果这里不需要 UI 权限判断，移除这个指令即可。

在 https://github.com/halo-dev/halo/pull/4598 之后才暴露这个问题是因为以前超管角色的 uiPermissions 是 *（代表拥有所有权限），但这个 PR 可能因为 PAT 的特性需要，会将角色拥有的所有角色模板的 ui permissions 列出提供给前端用于判断。

这个改动是必要的，已经暴露出了一些遗留问题，比如 https://github.com/halo-sigs/plugin-photos/issues/24#event-10581175653

**Comment by longjuan** [comment]
> 应该是和这行有关：
> 
> https://github.com/halo-dev/plugin-s3/blob/0265a71c83c677fd87eb02839958a4142dc72e23/console/src/views/HomeView.vue#L248
> 
> `system:users:aaa` 似乎没有在任何的 role template 中定义，如果这里不需要 UI 权限判断，移除这个指令即可。
> 
> 在 [halo-dev/halo#4598](https://github.com/halo-dev/halo/pull/4598) 之后才暴露这个问题是因为以前超管角色的 uiPermissions 是 *（代表拥有所有权限），但这个 PR 可能因为 PAT 的特性需要，会将角色拥有的所有角色模板的 ui permissions 列出提供给前端用于判断。
> 
> 这个改动是必要的，已经暴露出了一些遗留问题，比如 [halo-sigs/plugin-photos#24 (comment)](https://github.com/halo-sigs/plugin-photos/issues/24#event-10581175653)

感谢，确实是这个问题，当时抄代码的时候随手改了一个没注意。
之前考虑加上权限模板，但是页面移到插件详情页以后，没有插件管理权限就无法进入相应页面（插件查看权限也不行），有空了我提个issuse。

**Comment by ruibaby** [comment]
> 但是页面移到插件详情页以后，没有插件管理权限就无法进入相应页面（插件查看权限也不行）

现在有查看权限应该可以，应该是 2.9 之后 Console 部分的插件扩展加载就不需要插件查看权限了，因为已经把 Console 部分的扩展合并成了 bundle.js，所有登录用户都可以访问。

但这个关联功能既然放在了插件详情页面，是不是可以考虑直接依赖插件的查看权限？

cc @JohnNiang 

如果考虑到这个关联功能要开放给没有插件查看权限的人使用的话，可能放在插件详情的选项卡就不是很合适了。

**Comment by JohnNiang** [comment]
IMO，关联 S3 文件的功能入口如果能放置在下图中红色框处，会不会更好呢？

<img width="939" alt="image" src="https://github.com/halo-dev/plugin-s3/assets/16865714/459c8ea8-f615-40f8-a166-5c5c448033be">

如果当前用户有附件管理权限，则显示“关联 S3 文件”按钮，并进入对应的页面。
