### ISSUE TITLE
Request to release 1.5.0

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/plugin-s3#85]
由于必须包含 https://github.com/halo-dev/plugin-s3/pull/80 的改动才能够在 2.10 中正常运行，所以期望在 2.10 正式版之前发布此插件的新版本。

**Comment by longjuan** [comment]
你们发？

**Comment by longjuan** [comment]
1.5.1 版本中计划完善：
* 权限模板
* 解除关联 <https://github.com/halo-dev/halo/pull/4689>
* 同步移动端样式 <https://github.com/halo-dev/halo/pull/4587>
* 网址后缀
* readme修改

**Comment by ruibaby** [comment]
> 你们发？

我负责 request🤓

**Comment by ruibaby** [comment]
可以再测试一下，2.10.0 还有两天。

**Comment by ruibaby** [comment]
已发布。

https://github.com/halo-dev/plugin-s3/releases/tag/1.5.0

/close
